# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a5c7cf09dbd3cda2511331774f34dbe0a1ecc2dd67b809d15f57c3429290d8af914631bb0aae23aeb282ffd8038032f3dd8b0b974ca8e0fbadd2781a2cbb21d

test:
  secret_key_base: c767887be0a647526ba5e0d8239a4fe54c7d487b7a1a9dd6375e90fd42907d17cb61ad815b6ff74308089532eb371c1cf30eacefd28207fb71573e3cadf7bea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
